services:
  mysql:
    image: mysql:8.0
    ports:
      - "6433:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      ecotask-network:
        aliases:
          - mysql.ecotask.local

networks:
  ecotask-network:
    driver: bridge

volumes:
  mysql-data:
